services:

    web:
      image: django-ride-app
      container_name: ride_project_web
      build: .
      env_file: conf/environments/.env
      command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
      # stdin_open: true
      volumes:
      - .:/ride_project
      ports:
      - "9000:9000"
      - "4000:4000"
      expose:
      - "9000"
      sysctls:
      - net.ipv4.tcp_retries2=3